apiVersion: v1
kind: Service
metadata:
  name: email-sender-service
  labels:
    app: email-sender-service
    service: email-sender-service
spec:
  selector:
    app: email-sender-service
  ports:
    - port: 3006
      name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: email-sender-serviceaccount
  labels:
    account: email-sender-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-sender-deployment
  labels:
    app: email-sender-service
    version: v1
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: email-sender-service
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: email-sender-service
        version: v1
    spec:
      serviceAccountName: email-sender-serviceaccount
      containers:
        - name: email-sender-service
          image: 083118395813.dkr.ecr.ap-south-1.amazonaws.com/email-sender-service:latest
          ports:
            - containerPort: 3006
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: email-sender-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-sender-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

