apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
    service: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - port: 3000
      name: http
      targetPort: 3000  
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-serviceaccount
  labels:
    account: frontend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-service
    version: v1
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: frontend-service
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: frontend-service
        version: v1
    spec:
      serviceAccountName: frontend-serviceaccount
      containers: 
        - name: frontend-service
          image: 083118395813.dkr.ecr.ap-south-1.amazonaws.com/frontend-service:latest
          ports:
            - containerPort: 3000
