apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: messaging-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"                                                                                                                                                                                                                   
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: messaging-virtualservice
spec:
  gateways:
  - messaging-gateway
  hosts:
  - "a35aa8106631548999edb5d5731f034f-1793418561.ap-south-1.elb.amazonaws.com"
  http:
  - route:
    - destination:
        host: frontend-service
        port:
          number: 3000
