apiVersion: v1
kind: Service
metadata:
  name: greetings-manager-service
  labels:
    app: greetings-manager-service
    service: greetings-manager-service
spec:
  selector:
    app: greetings-manager-service
  ports:
    - port: 3000
      name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greetings-manager-serviceaccount
  labels:
    account: greetings-manager-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-manager-deployment
  labels:
    app: greetings-manager
    version: v1
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: greetings-manager-service
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: greetings-manager-service
        version: v1
    spec:
      serviceAccountName: greetings-manager-serviceaccount
      containers:
        - name: greetings-manager-service
          image: 083118395813.dkr.ecr.ap-south-1.amazonaws.com/greetings-manager-service:latest
          ports:
            - containerPort: 3000
