apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  labels:
    app: scheduler-service
    service: scheduler-service
spec:
  selector:
    app: scheduler-service
  ports:
    - port: 3008
      name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-serviceaccount
  labels:
    account: scheduler-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler-service
    version: v1
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: scheduler-service
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: scheduler-service
        version: v1
    spec:
      serviceAccountName: scheduler-serviceaccount
      containers:
        - name: scheduler-service
          image: 083118395813.dkr.ecr.ap-south-1.amazonaws.com/scheduler-service:latest
          ports:
            - containerPort: 3008
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scheduler-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scheduler-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
