apiVersion: v1
kind: Service
metadata:
  name: whatsapp-sender-service
  labels:
    app: whatsapp-sender-service
    service: whatsapp-sender-service
spec:
  selector:
    app: whatsapp-sender-service
  ports:
    - port: 3010
      name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatsapp-sender-serviceaccount
  labels:
    account: whatsapp-sender-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-sender-deployment
  labels:
    app: whatsapp-sender-service
    version: v1
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: whatsapp-sender-service
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: whatsapp-sender-service
        version: v1
    spec:
      serviceAccountName: whatsapp-sender-serviceaccount
      containers:
        - name: whatsapp-sender-service
          image: 083118395813.dkr.ecr.ap-south-1.amazonaws.com/whatsapp-sender-service:latest
          ports:
            - containerPort: 3010
